server:
  port: 80

spring:

  thymeleaf:
    mode: HTML

  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=true
    username: root
    password: Aa995511.
# 用于通过IP查找地址的百度API
baiduApi:
  accessKey: 
  secretKey: 
# 用于微信推送消息
pushMessage:
  token: 
